package net.bodz.bas.c.system;

public class SystemProperties {

    public static boolean developMode;
    static {
        String devmode = System.getenv("DEVELOP_MODE");
        if (devmode == null)
            devmode = System.getProperty("DEVELOP_MODE");
        if ("1".equals(devmode))
            developMode = true;
    }

    public static boolean isDevelopMode() {
        return developMode;
    }

    /**
     * Generated by {@link SystemPropertiesTest#generate()}
     */
    static String generator = "class net.bodz.bas.sys.SystemPropertiesTest";

    /** awt.toolkit = sun.awt.windows.WToolkit */
    public static String getAwtToolkit() {
        return System.getProperty("awt.toolkit");
    }

    /** file.encoding = UTF-8 */
    public static String getFileEncoding() {
        return System.getProperty("file.encoding");
    }

    /** file.encoding.pkg = sun.io */
    public static String getFileEncodingPkg() {
        return System.getProperty("file.encoding.pkg");
    }

    /** file.separator = / */
    public static String getFileSeparator() {
        return System.getProperty("file.separator");
    }

    /** java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment */
    public static String getJavaAwtGraphicsenv() {
        return System.getProperty("java.awt.graphicsenv");
    }

    /** java.awt.printerjob = sun.awt.windows.WPrinterJob */
    public static String getJavaAwtPrinterjob() {
        return System.getProperty("java.awt.printerjob");
    }

    /**
     * java.class.path =...
     */
    public static String getJavaClassPath() {
        return System.getProperty("java.class.path");
    }

    /** java.class.version = 51.0 */
    public static String getJavaClassVersion() {
        return System.getProperty("java.class.version");
    }

    /**
     * java.endorsed.dirs = C:/lam/kala/abc.d/j/jdk-1.7.0/jre/lib/endorsed
     */
    public static String getJavaEndorsedDirs() {
        return System.getProperty("java.endorsed.dirs");
    }

    /**
     * java.ext.dirs = C:/lam/kala/abc.d/j/jdk-1.7.0/jre/lib/ext;C:/WINDOWS /Sun/Java/lib/ext
     */
    public static String getJavaExtDirs() {
        return System.getProperty("java.ext.dirs");
    }

    /** java.home = C:/lam/kala/abc.d/j/jdk-1.7.0/jre */
    public static String getJavaHome() {
        return System.getProperty("java.home");
    }

    /** java.io.tmpdir = C:/Profiles/Shecti/Temp/ */
    public static String getJavaIoTmpdir() {
        return System.getProperty("java.io.tmpdir");
    }

    /**
     * java.library.path = ...
     */
    public static String getJavaLibraryPath() {
        return System.getProperty("java.library.path");
    }

    /** java.runtime.name = Java(TM) SE Runtime Environment */
    public static String getJavaRuntimeName() {
        return System.getProperty("java.runtime.name");
    }

    /** java.runtime.version = 1.7.0-ea-b53 */
    public static String getJavaRuntimeVersion() {
        return System.getProperty("java.runtime.version");
    }

    /** java.specification.name = Java Platform API Specification */
    public static String getJavaSpecificationName() {
        return System.getProperty("java.specification.name");
    }

    /** java.specification.vendor = Sun Microsystems Inc. */
    public static String getJavaSpecificationVendor() {
        return System.getProperty("java.specification.vendor");
    }

    /** java.specification.version = 1.7 */
    public static String getJavaSpecificationVersion() {
        return System.getProperty("java.specification.version");
    }

    /** java.vendor = Sun Microsystems Inc. */
    public static String getJavaVendor() {
        return System.getProperty("java.vendor");
    }

    /** java.vendor.url = http://java.sun.com/ */
    public static String getJavaVendorUrl() {
        return System.getProperty("java.vendor.url");
    }

    /** java.vendor.url.bug = http://java.sun.com/cgi-bin/bugreport.cgi */
    public static String getJavaVendorUrlBug() {
        return System.getProperty("java.vendor.url.bug");
    }

    /** java.version = 1.7.0-ea */
    public static String getJavaVersion() {
        return System.getProperty("java.version");
    }

    /** java.vm.info = mixed mode, sharing */
    public static String getJavaVmInfo() {
        return System.getProperty("java.vm.info");
    }

    /** java.vm.name = Java HotSpot(TM) Client VM */
    public static String getJavaVmName() {
        return System.getProperty("java.vm.name");
    }

    /** java.vm.specification.name = Java Virtual Machine Specification */
    public static String getJavaVmSpecificationName() {
        return System.getProperty("java.vm.specification.name");
    }

    /** java.vm.specification.vendor = Sun Microsystems Inc. */
    public static String getJavaVmSpecificationVendor() {
        return System.getProperty("java.vm.specification.vendor");
    }

    /** java.vm.specification.version = 1.0 */
    public static String getJavaVmSpecificationVersion() {
        return System.getProperty("java.vm.specification.version");
    }

    /** java.vm.vendor = Sun Microsystems Inc. */
    public static String getJavaVmVendor() {
        return System.getProperty("java.vm.vendor");
    }

    /** java.vm.version = 15.0-b04 */
    public static String getJavaVmVersion() {
        return System.getProperty("java.vm.version");
    }

    /** line.separator = \r\n */
    public static String getLineSeparator() {
        return System.getProperty("line.separator");
    }

    /** os.arch = x86 */
    public static String getOsArch() {
        return System.getProperty("os.arch");
    }

    /** os.name = Windows XP */
    public static String getOsName() {
        return System.getProperty("os.name");
    }

    /** os.version = 5.1 */
    public static String getOsVersion() {
        return System.getProperty("os.version");
    }

    /** path.separator = ; */
    public static String getPathSeparator() {
        return System.getProperty("path.separator");
    }

    /** sun.arch.data.model = 32 */
    public static String getSunArchDataModel() {
        return System.getProperty("sun.arch.data.model");
    }

    /**
     * sun.boot.class.path = C:/lam/kala/abc.d/j/jdk-1.7.0/jre/lib/resources .jar;C:/lam/kala\
     * \abc.d/j/jdk-1.7.0/jre/lib/rt.jar;C:/lam/kala/abc .d/j/jdk-1.7.0/
     * jre/lib/sunrsasign.jar;C:/lam/kala/abc.d/j/jdk-1.7 .0/jre/lib/jsse
     * .jar;C:/lam/kala/abc.d/j/jdk-1.7.0/jre/lib/jce.jar ;C:/lam/kala/abc
     * .d/j/jdk-1.7.0/jre/lib/charsets.jar;C:/lam/kala/ abc.d/j/jdk-1.7.0/jre/classes
     */
    public static String getSunBootClassPath() {
        return System.getProperty("sun.boot.class.path");
    }

    /** sun.boot.library.path = C:/lam/kala/abc.d/j/jdk-1.7.0/jre/bin */
    public static String getSunBootLibraryPath() {
        return System.getProperty("sun.boot.library.path");
    }

    /** sun.cpu.endian = little */
    public static String getSunCpuEndian() {
        return System.getProperty("sun.cpu.endian");
    }

    /** sun.cpu.isalist = */
    public static String getSunCpuIsalist() {
        return System.getProperty("sun.cpu.isalist");
    }

    /** sun.desktop = windows */
    public static String getSunDesktop() {
        return System.getProperty("sun.desktop");
    }

    /** sun.io.unicode.encoding = UnicodeLittle */
    public static String getSunIoUnicodeEncoding() {
        return System.getProperty("sun.io.unicode.encoding");
    }

    /** sun.java.launcher = SUN_STANDARD */
    public static String getSunJavaLauncher() {
        return System.getProperty("sun.java.launcher");
    }

    /** sun.jnu.encoding = GBK */
    public static String getSunJnuEncoding() {
        return System.getProperty("sun.jnu.encoding");
    }

    /** sun.management.compiler = HotSpot Client Compiler */
    public static String getSunManagementCompiler() {
        return System.getProperty("sun.management.compiler");
    }

    /** sun.os.patch.level = Service Pack 3, v.5755 */
    public static String getSunOsPatchLevel() {
        return System.getProperty("sun.os.patch.level");
    }

    /** user.country = CN */
    public static String getUserCountry() {
        return System.getProperty("user.country");
    }

    /** user.dir = K:/workspace/net.bodz/net.bodz.bas */
    public static String getUserDir() {
        return System.getProperty("user.dir");
    }

    /** user.home = C:/Profiles/Shecti */
    public static String getUserHome() {
        return System.getProperty("user.home");
    }

    /** user.language = zh */
    public static String getUserLanguage() {
        return System.getProperty("user.language");
    }

    /** user.name = Shecti */
    public static String getUserName() {
        return System.getProperty("user.name");
    }

    /** user.timezone = */
    public static String getUserTimezone() {
        return System.getProperty("user.timezone");
    }

    /** user.variant = */
    public static String getUserVariant() {
        return System.getProperty("user.variant");
    }

}
