package net.bodz.bas.sys;

/**
 * @test {@link SystemPropertiesTest}
 */
public class SystemProperties {

    public static boolean developMode;
    static {
        String devmode = System.getenv("DEVELOP_MODE"); //$NON-NLS-1$
        if (devmode == null)
            devmode = System.getProperty("DEVELOP_MODE"); //$NON-NLS-1$
        if ("1".equals(devmode)) //$NON-NLS-1$
            developMode = true;
    }

    public static boolean isDevelopMode() {
        return developMode;
    }

    /**
     * Generated by {@link SystemPropertiesTest#generate()}
     */
    static String generator = "class net.bodz.bas.sys.SystemPropertiesTest"; //$NON-NLS-1$

    /** awt.toolkit = sun.awt.windows.WToolkit */
    public static String getAwtToolkit() {
        return System.getProperty("awt.toolkit"); //$NON-NLS-1$
    }

    /** file.encoding = UTF-8 */
    public static String getFileEncoding() {
        return System.getProperty("file.encoding"); //$NON-NLS-1$
    }

    /** file.encoding.pkg = sun.io */
    public static String getFileEncodingPkg() {
        return System.getProperty("file.encoding.pkg"); //$NON-NLS-1$
    }

    /** file.separator = \\ */
    public static String getFileSeparator() {
        return System.getProperty("file.separator"); //$NON-NLS-1$
    }

    /** java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment */
    public static String getJavaAwtGraphicsenv() {
        return System.getProperty("java.awt.graphicsenv"); //$NON-NLS-1$
    }

    /** java.awt.printerjob = sun.awt.windows.WPrinterJob */
    public static String getJavaAwtPrinterjob() {
        return System.getProperty("java.awt.printerjob"); //$NON-NLS-1$
    }

    /**
     * java.class.path =...
     */
    public static String getJavaClassPath() {
        return System.getProperty("java.class.path"); //$NON-NLS-1$
    }

    /** java.class.version = 51.0 */
    public static String getJavaClassVersion() {
        return System.getProperty("java.class.version"); //$NON-NLS-1$
    }

    /**
     * java.endorsed.dirs = C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre\\lib\\endorsed
     */
    public static String getJavaEndorsedDirs() {
        return System.getProperty("java.endorsed.dirs"); //$NON-NLS-1$
    }

    /**
     * java.ext.dirs = C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre\\lib\\ext;C:\\WINDOWS
     * \\Sun\\Java\\lib\\ext
     */
    public static String getJavaExtDirs() {
        return System.getProperty("java.ext.dirs"); //$NON-NLS-1$
    }

    /** java.home = C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre */
    public static String getJavaHome() {
        return System.getProperty("java.home"); //$NON-NLS-1$
    }

    /** java.io.tmpdir = C:\\Profiles\\Shecti\\Temp\\ */
    public static String getJavaIoTmpdir() {
        return System.getProperty("java.io.tmpdir"); //$NON-NLS-1$
    }

    /**
     * java.library.path = ...
     */
    public static String getJavaLibraryPath() {
        return System.getProperty("java.library.path"); //$NON-NLS-1$
    }

    /** java.runtime.name = Java(TM) SE Runtime Environment */
    public static String getJavaRuntimeName() {
        return System.getProperty("java.runtime.name"); //$NON-NLS-1$
    }

    /** java.runtime.version = 1.7.0-ea-b53 */
    public static String getJavaRuntimeVersion() {
        return System.getProperty("java.runtime.version"); //$NON-NLS-1$
    }

    /** java.specification.name = Java Platform API Specification */
    public static String getJavaSpecificationName() {
        return System.getProperty("java.specification.name"); //$NON-NLS-1$
    }

    /** java.specification.vendor = Sun Microsystems Inc. */
    public static String getJavaSpecificationVendor() {
        return System.getProperty("java.specification.vendor"); //$NON-NLS-1$
    }

    /** java.specification.version = 1.7 */
    public static String getJavaSpecificationVersion() {
        return System.getProperty("java.specification.version"); //$NON-NLS-1$
    }

    /** java.vendor = Sun Microsystems Inc. */
    public static String getJavaVendor() {
        return System.getProperty("java.vendor"); //$NON-NLS-1$
    }

    /** java.vendor.url = http://java.sun.com/ */
    public static String getJavaVendorUrl() {
        return System.getProperty("java.vendor.url"); //$NON-NLS-1$
    }

    /** java.vendor.url.bug = http://java.sun.com/cgi-bin/bugreport.cgi */
    public static String getJavaVendorUrlBug() {
        return System.getProperty("java.vendor.url.bug"); //$NON-NLS-1$
    }

    /** java.version = 1.7.0-ea */
    public static String getJavaVersion() {
        return System.getProperty("java.version"); //$NON-NLS-1$
    }

    /** java.vm.info = mixed mode, sharing */
    public static String getJavaVmInfo() {
        return System.getProperty("java.vm.info"); //$NON-NLS-1$
    }

    /** java.vm.name = Java HotSpot(TM) Client VM */
    public static String getJavaVmName() {
        return System.getProperty("java.vm.name"); //$NON-NLS-1$
    }

    /** java.vm.specification.name = Java Virtual Machine Specification */
    public static String getJavaVmSpecificationName() {
        return System.getProperty("java.vm.specification.name"); //$NON-NLS-1$
    }

    /** java.vm.specification.vendor = Sun Microsystems Inc. */
    public static String getJavaVmSpecificationVendor() {
        return System.getProperty("java.vm.specification.vendor"); //$NON-NLS-1$
    }

    /** java.vm.specification.version = 1.0 */
    public static String getJavaVmSpecificationVersion() {
        return System.getProperty("java.vm.specification.version"); //$NON-NLS-1$
    }

    /** java.vm.vendor = Sun Microsystems Inc. */
    public static String getJavaVmVendor() {
        return System.getProperty("java.vm.vendor"); //$NON-NLS-1$
    }

    /** java.vm.version = 15.0-b04 */
    public static String getJavaVmVersion() {
        return System.getProperty("java.vm.version"); //$NON-NLS-1$
    }

    /** line.separator = \r\n */
    public static String getLineSeparator() {
        return System.getProperty("line.separator"); //$NON-NLS-1$
    }

    /** os.arch = x86 */
    public static String getOsArch() {
        return System.getProperty("os.arch"); //$NON-NLS-1$
    }

    /** os.name = Windows XP */
    public static String getOsName() {
        return System.getProperty("os.name"); //$NON-NLS-1$
    }

    /** os.version = 5.1 */
    public static String getOsVersion() {
        return System.getProperty("os.version"); //$NON-NLS-1$
    }

    /** path.separator = ; */
    public static String getPathSeparator() {
        return System.getProperty("path.separator"); //$NON-NLS-1$
    }

    /** sun.arch.data.model = 32 */
    public static String getSunArchDataModel() {
        return System.getProperty("sun.arch.data.model"); //$NON-NLS-1$
    }

    /**
     * sun.boot.class.path = C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre\\lib\\resources
     * .jar;C:\\lam\\kala\ \abc.d\\j\\jdk-1.7.0\\jre\\lib\\rt.jar;C:\\lam\\kala\\abc
     * .d\\j\\jdk-1.7.0\\ jre\\lib\\sunrsasign.jar;C:\\lam\\kala\\abc.d\\j\\jdk-1.7
     * .0\\jre\\lib\\jsse .jar;C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre\\lib\\jce.jar
     * ;C:\\lam\\kala\\abc .d\\j\\jdk-1.7.0\\jre\\lib\\charsets.jar;C:\\lam\\kala\\
     * abc.d\\j\\jdk-1.7.0\\jre\\classes
     */
    public static String getSunBootClassPath() {
        return System.getProperty("sun.boot.class.path"); //$NON-NLS-1$
    }

    /** sun.boot.library.path = C:\\lam\\kala\\abc.d\\j\\jdk-1.7.0\\jre\\bin */
    public static String getSunBootLibraryPath() {
        return System.getProperty("sun.boot.library.path"); //$NON-NLS-1$
    }

    /** sun.cpu.endian = little */
    public static String getSunCpuEndian() {
        return System.getProperty("sun.cpu.endian"); //$NON-NLS-1$
    }

    /** sun.cpu.isalist = */
    public static String getSunCpuIsalist() {
        return System.getProperty("sun.cpu.isalist"); //$NON-NLS-1$
    }

    /** sun.desktop = windows */
    public static String getSunDesktop() {
        return System.getProperty("sun.desktop"); //$NON-NLS-1$
    }

    /** sun.io.unicode.encoding = UnicodeLittle */
    public static String getSunIoUnicodeEncoding() {
        return System.getProperty("sun.io.unicode.encoding"); //$NON-NLS-1$
    }

    /** sun.java.launcher = SUN_STANDARD */
    public static String getSunJavaLauncher() {
        return System.getProperty("sun.java.launcher"); //$NON-NLS-1$
    }

    /** sun.jnu.encoding = GBK */
    public static String getSunJnuEncoding() {
        return System.getProperty("sun.jnu.encoding"); //$NON-NLS-1$
    }

    /** sun.management.compiler = HotSpot Client Compiler */
    public static String getSunManagementCompiler() {
        return System.getProperty("sun.management.compiler"); //$NON-NLS-1$
    }

    /** sun.os.patch.level = Service Pack 3, v.5755 */
    public static String getSunOsPatchLevel() {
        return System.getProperty("sun.os.patch.level"); //$NON-NLS-1$
    }

    /** user.country = CN */
    public static String getUserCountry() {
        return System.getProperty("user.country"); //$NON-NLS-1$
    }

    /** user.dir = K:\\workspace\\net.bodz\\net.bodz.bas */
    public static String getUserDir() {
        return System.getProperty("user.dir"); //$NON-NLS-1$
    }

    /** user.home = C:\\Profiles\\Shecti */
    public static String getUserHome() {
        return System.getProperty("user.home"); //$NON-NLS-1$
    }

    /** user.language = zh */
    public static String getUserLanguage() {
        return System.getProperty("user.language"); //$NON-NLS-1$
    }

    /** user.name = Shecti */
    public static String getUserName() {
        return System.getProperty("user.name"); //$NON-NLS-1$
    }

    /** user.timezone = */
    public static String getUserTimezone() {
        return System.getProperty("user.timezone"); //$NON-NLS-1$
    }

    /** user.variant = */
    public static String getUserVariant() {
        return System.getProperty("user.variant"); //$NON-NLS-1$
    }

}
