include coolmake/catrst.mf
include coolmake/catsql.mf

all: \
        out/lily.rst \
        out/lily.sql \
        out/lily.lst \
        out/violet.rst \
        out/violet.sql \
        out/violet.lst \
        out/fab.rst \
        out/fab.sql \
        out/fab.lst
	cat out/violet.sql | xsel -b

