<?php
/*
 * warning:  this file is automatically generated by m4 scripts.  please do not edit this file, you may lose all your changes in this file after the original file is re-built.  
 */

require '_Phpfixes.php'; 
_RequireOnce('t-config.php'); 
_RequireOnce('../pdo.php'); 

class person extends phpx_data_object {
    var $pdt_name = 41218 /*NOTNULL,CDATA,GET,PRIMARY*/; 
    # pdo_primary_key(`name'); 
    
    var $pdt_age = 16385 /*RAW,VERIFY*/; 
    var $pdv_age = 0; 
    
    var $pdt_address = 2 /*CDATA*/; 
    
    function get_name() {
        return 'I am always Jim\'TOMMY!'; 
    }
    
    function vrf_age() {
        $age = $this->get('age'); 
        if ($age > 100)
            return "Age could not be greater than 1000!!"; 
        return NULL; 
    }
    
    function dump() {
        return 'Person(name='.$this->get('name').', age='.$this->get('age').')'; 
    }
    
}

$p = new person; 
echo 'name: ', $p->get('name'), "\n"; 
$p->put('name', NULL);

echo "--------------------- format: \n";
echo $p->_format_debug(); 

?>