application: bodzed
version: 1
runtime: python
api_version: 1

# default_expiration: "24h"

handlers:
- url: /
  script: index.py

- url: /(.*\.py)
  script: \1

- url: /([a-z]/.*(\.xml|xsl|xslt|dtd|xsd))
  static_files: models/\1
  mime_type: text/xml
  upload: models/.*(\.xml|xsl|xslt|dtd|xsd)

- url: /.*
  script: not_found.py
