import { createRouter, createWebHashHistory } from 'vue-router';

export const links = {
    "Index": "component Index",
    "Project": "component Project",
    "GroupAdmin": "component GroupAdmin",
    "GroupTypeAdmin": "component GroupTypeAdmin",
    "PolicyAdmin": "component PolicyAdmin",
    "UserAdmin": "component UserAdmin",
    "UserOtherIdAdmin": "component UserOtherIdAdmin",
    "UserOtherIdTypeAdmin": "component UserOtherIdTypeAdmin",
    "UserRunAdmin": "component UserRunAdmin",
    "UserSecretAdmin": "component UserSecretAdmin",
    "UserTypeAdmin": "component UserTypeAdmin",
    "OrgUnitAdmin": "component OrgUnitAdmin",
    "OrganizationAdmin": "component OrganizationAdmin",
    "PartyCategoryAdmin": "component PartyCategoryAdmin",
    "PersonAdmin": "component PersonAdmin",
    "PersonRoleAdmin": "component PersonRoleAdmin",
    "PersonTagAdmin": "component PersonTagAdmin",
    "PersonTagTypeAdmin": "component PersonTagTypeAdmin",
    "ZoneAdmin": "component ZoneAdmin",
    "ZoneCategoryAdmin": "component ZoneCategoryAdmin",
    "ExternalSiteAdmin": "component ExternalSiteAdmin",
    "StorageAdmin": "component StorageAdmin",
    "CategoryDefAdmin": "component CategoryDefAdmin",
    "FormDefAdmin": "component FormDefAdmin",
    "FormParameterAdmin": "component FormParameterAdmin",
    "ParameterDefAdmin": "component ParameterDefAdmin",
    "ParameterValueAdmin": "component ParameterValueAdmin",
    "PhaseDefAdmin": "component PhaseDefAdmin",
    "SchemaDefAdmin": "component SchemaDefAdmin",
    "TagDefAdmin": "component TagDefAdmin",
    "TagGroupDefAdmin": "component TagGroupDefAdmin",
    "ArticleAdmin": "component ArticleAdmin",
    "ArticleBackrefAdmin": "component ArticleBackrefAdmin",
    "ArticleCategoryAdmin": "component ArticleCategoryAdmin",
    "ArticleFavAdmin": "component ArticleFavAdmin",
    "ArticleParameterAdmin": "component ArticleParameterAdmin",
    "ArticleParameterTypeAdmin": "component ArticleParameterTypeAdmin",
    "ArticleTagAdmin": "component ArticleTagAdmin",
    "ArticleTagTypeAdmin": "component ArticleTagTypeAdmin",
    "ArticleTalkAdmin": "component ArticleTalkAdmin",
    "ArticleTalkVoteAdmin": "component ArticleTalkVoteAdmin",
    "ArticleVoteAdmin": "component ArticleVoteAdmin",
    "PostAdmin": "component PostAdmin",
    "PostBackrefAdmin": "component PostBackrefAdmin",
    "PostCategoryAdmin": "component PostCategoryAdmin",
    "PostFavAdmin": "component PostFavAdmin",
    "PostParameterAdmin": "component PostParameterAdmin",
    "PostParameterTypeAdmin": "component PostParameterTypeAdmin",
    "PostTagAdmin": "component PostTagAdmin",
    "PostTagTypeAdmin": "component PostTagTypeAdmin",
    "PostTalkAdmin": "component PostTalkAdmin",
    "PostTalkVoteAdmin": "component PostTalkVoteAdmin",
    "PostVoteAdmin": "component PostVoteAdmin",
    "BadgeAdmin": "component BadgeAdmin",
    "UserBadgeAdmin": "component UserBadgeAdmin",
    "UomAdmin": "component UomAdmin",
    "ApiTypeAdmin": "component ApiTypeAdmin",
    "VApiAdmin": "component VApiAdmin",
    "VApiCreditAdmin": "component VApiCreditAdmin",
    "VApiLogAdmin": "component VApiLogAdmin",
    "VAppAdmin": "component VAppAdmin",
    "VAppCatAdmin": "component VAppCatAdmin",
    "VAppRequestAdmin": "component VAppRequestAdmin",
    "VAppRequestApiAdmin": "component VAppRequestApiAdmin",
};

const router = createRouter({
    history: createWebHashHistory(),
    routes: [
        { path: '/', component: () => import('./Index.vue') },
        { path: '/Project', component: () => import('@skeljs/core/src/ui/demo/Project.vue') },
        { path: '/GroupAdmin', component: () => import('../src/net/bodz/lily/schema/account/GroupAdmin.vue') },
        { path: '/GroupTypeAdmin', component: () => import('../src/net/bodz/lily/schema/account/GroupTypeAdmin.vue') },
        { path: '/PolicyAdmin', component: () => import('../src/net/bodz/lily/schema/account/PolicyAdmin.vue') },
        { path: '/UserAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserAdmin.vue') },
        { path: '/UserOtherIdAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserOtherIdAdmin.vue') },
        { path: '/UserOtherIdTypeAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserOtherIdTypeAdmin.vue') },
        { path: '/UserRunAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserRunAdmin.vue') },
        { path: '/UserSecretAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserSecretAdmin.vue') },
        { path: '/UserTypeAdmin', component: () => import('../src/net/bodz/lily/schema/account/UserTypeAdmin.vue') },
        { path: '/OrgUnitAdmin', component: () => import('../src/net/bodz/lily/schema/contact/OrgUnitAdmin.vue') },
        { path: '/OrganizationAdmin', component: () => import('../src/net/bodz/lily/schema/contact/OrganizationAdmin.vue') },
        { path: '/PartyCategoryAdmin', component: () => import('../src/net/bodz/lily/schema/contact/PartyCategoryAdmin.vue') },
        { path: '/PersonAdmin', component: () => import('../src/net/bodz/lily/schema/contact/PersonAdmin.vue') },
        { path: '/PersonRoleAdmin', component: () => import('../src/net/bodz/lily/schema/contact/PersonRoleAdmin.vue') },
        { path: '/PersonTagAdmin', component: () => import('../src/net/bodz/lily/schema/contact/PersonTagAdmin.vue') },
        { path: '/PersonTagTypeAdmin', component: () => import('../src/net/bodz/lily/schema/contact/PersonTagTypeAdmin.vue') },
        { path: '/ZoneAdmin', component: () => import('../src/net/bodz/lily/schema/geo/ZoneAdmin.vue') },
        { path: '/ZoneCategoryAdmin', component: () => import('../src/net/bodz/lily/schema/geo/ZoneCategoryAdmin.vue') },
        { path: '/ExternalSiteAdmin', component: () => import('../src/net/bodz/lily/schema/inet/ExternalSiteAdmin.vue') },
        { path: '/StorageAdmin', component: () => import('../src/net/bodz/lily/schema/io/StorageAdmin.vue') },
        { path: '/CategoryDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/CategoryDefAdmin.vue') },
        { path: '/FormDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/FormDefAdmin.vue') },
        { path: '/FormParameterAdmin', component: () => import('../src/net/bodz/lily/schema/meta/FormParameterAdmin.vue') },
        { path: '/ParameterDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/ParameterDefAdmin.vue') },
        { path: '/ParameterValueAdmin', component: () => import('../src/net/bodz/lily/schema/meta/ParameterValueAdmin.vue') },
        { path: '/PhaseDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/PhaseDefAdmin.vue') },
        { path: '/SchemaDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/SchemaDefAdmin.vue') },
        { path: '/TagDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/TagDefAdmin.vue') },
        { path: '/TagGroupDefAdmin', component: () => import('../src/net/bodz/lily/schema/meta/TagGroupDefAdmin.vue') },
        { path: '/ArticleAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleAdmin.vue') },
        { path: '/ArticleBackrefAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleBackrefAdmin.vue') },
        { path: '/ArticleCategoryAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleCategoryAdmin.vue') },
        { path: '/ArticleFavAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleFavAdmin.vue') },
        { path: '/ArticleParameterAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleParameterAdmin.vue') },
        { path: '/ArticleParameterTypeAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleParameterTypeAdmin.vue') },
        { path: '/ArticleTagAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleTagAdmin.vue') },
        { path: '/ArticleTagTypeAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleTagTypeAdmin.vue') },
        { path: '/ArticleTalkAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleTalkAdmin.vue') },
        { path: '/ArticleTalkVoteAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleTalkVoteAdmin.vue') },
        { path: '/ArticleVoteAdmin', component: () => import('../src/net/bodz/lily/schema/pub/ArticleVoteAdmin.vue') },
        { path: '/PostAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostAdmin.vue') },
        { path: '/PostBackrefAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostBackrefAdmin.vue') },
        { path: '/PostCategoryAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostCategoryAdmin.vue') },
        { path: '/PostFavAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostFavAdmin.vue') },
        { path: '/PostParameterAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostParameterAdmin.vue') },
        { path: '/PostParameterTypeAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostParameterTypeAdmin.vue') },
        { path: '/PostTagAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostTagAdmin.vue') },
        { path: '/PostTagTypeAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostTagTypeAdmin.vue') },
        { path: '/PostTalkAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostTalkAdmin.vue') },
        { path: '/PostTalkVoteAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostTalkVoteAdmin.vue') },
        { path: '/PostVoteAdmin', component: () => import('../src/net/bodz/lily/schema/pub/PostVoteAdmin.vue') },
        { path: '/BadgeAdmin', component: () => import('../src/net/bodz/lily/schema/reward/BadgeAdmin.vue') },
        { path: '/UserBadgeAdmin', component: () => import('../src/net/bodz/lily/schema/reward/UserBadgeAdmin.vue') },
        { path: '/UomAdmin', component: () => import('../src/net/bodz/lily/schema/util/UomAdmin.vue') },
        { path: '/ApiTypeAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/ApiTypeAdmin.vue') },
        { path: '/VApiAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VApiAdmin.vue') },
        { path: '/VApiCreditAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VApiCreditAdmin.vue') },
        { path: '/VApiLogAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VApiLogAdmin.vue') },
        { path: '/VAppAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VAppAdmin.vue') },
        { path: '/VAppCatAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VAppCatAdmin.vue') },
        { path: '/VAppRequestAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VAppRequestAdmin.vue') },
        { path: '/VAppRequestApiAdmin', component: () => import('../src/net/bodz/lily/schema/vapp/VAppRequestApiAdmin.vue') },
    ]
});

export default router;
