//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.25 at 12:13:34 ÏÂÎç CST 
//


package net.bodz.xml.models.pdb.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.bodz.xml.models.pdb.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.bodz.xml.models.pdb.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pdb.Import }
     * 
     */
    public Pdb.Import createPdbImport() {
        return new Pdb.Import();
    }

    /**
     * Create an instance of {@link View.GroupBy }
     * 
     */
    public View.GroupBy createViewGroupBy() {
        return new View.GroupBy();
    }

    /**
     * Create an instance of {@link Table.Check }
     * 
     */
    public Table.Check createTableCheck() {
        return new Table.Check();
    }

    /**
     * Create an instance of {@link FromType.Ref }
     * 
     */
    public FromType.Ref createFromTypeRef() {
        return new FromType.Ref();
    }

    /**
     * Create an instance of {@link Table.Instance }
     * 
     */
    public Table.Instance createTableInstance() {
        return new Table.Instance();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link View.Sort }
     * 
     */
    public View.Sort createViewSort() {
        return new View.Sort();
    }

    /**
     * Create an instance of {@link FromType.Join }
     * 
     */
    public FromType.Join createFromTypeJoin() {
        return new FromType.Join();
    }

    /**
     * Create an instance of {@link Table.Field }
     * 
     */
    public Table.Field createTableField() {
        return new Table.Field();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link FromType }
     * 
     */
    public FromType createFromType() {
        return new FromType();
    }

    /**
     * Create an instance of {@link View.Field }
     * 
     */
    public View.Field createViewField() {
        return new View.Field();
    }

    /**
     * Create an instance of {@link Table.Index }
     * 
     */
    public Table.Index createTableIndex() {
        return new Table.Index();
    }

    /**
     * Create an instance of {@link Table.Trigger }
     * 
     */
    public Table.Trigger createTableTrigger() {
        return new Table.Trigger();
    }

    /**
     * Create an instance of {@link Pdb }
     * 
     */
    public Pdb createPdb() {
        return new Pdb();
    }

}
