//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.25 at 12:13:34 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.bodz.net/p/pdb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.bodz.xml.models.pdb.jaxb;
