<?
/*
 * warning:  this file is automatically generated by m4 scripts.  please do not edit this file, you may lose all your changes in this file after the original file is re-built.  
 */

/* Common-PHP
 *
 * SMTP Class
 * 
 * $Id: mail.php,v 1.2 2005-08-07 13:02:47 dansei Exp $
 * $Log: not supported by cvs2svn $
 * Revision 1.1  2005/08/05 06:03:32  dansei
 * dev pack.
 *
 * Revision 1.1  2005/07/30 05:20:10  dansei
 * initial
 *
 */
require '_Phpfixes.php'; 
_RequireOnce("ext/phpmailer.php"); 

class phpx_mail extends PHPMailer {
    var $Mailer     = 'smtp'; 
    var $Host       = '61.152.93.15'; 
    var $Username   = 'mlv@vsdn.net'; 
    var $Password   = 'nothing'; 
    var $SMTPAuth   = true; 
    var $From       = 'mlv@pfpf.net'; 
    var $FromName   = 'MLV Support'; 
    var $CharSet    = 'UTF-8'; 
    var $ReplyTo    = array('lenik@bodz.net'); 
}

?>