import { createRouter, createWebHashHistory } from 'vue-router';

export const links = {
    "": "component ",
    "Project": "component Project",
    "ArtifactAdmin": "Admin view of: Artifact",
    "ArtifactBackrefAdmin": "Admin view of: Artifact backref",
    "ArtifactCategoryAdmin": "Admin view of: Artifact category",
    "ArtifactDocAdmin": "Admin view of: Artifact doc",
    "ArtifactParamAdmin": "Admin view of: Artifact param",
    "ArtifactPhaseAdmin": "Admin view of: Artifact phase",
    "ArtifactTagAdmin": "Admin view of: Artifact tag",
    "ArtifactTypeAdmin": "Admin view of: Artifact type",
    "ArtifactTypeParamAdmin": "Admin view of: Artifact type param",
    "ArtifactVoteAdmin": "Admin view of: Artifact vote",
    "StdParameterAdmin": "Admin view of: Std parameter",
    "AssetAdmin": "Admin view of: Asset",
    "GroupAssetAdmin": "Admin view of: Group asset",
    "OrgAssetAdmin": "Admin view of: Org asset",
    "OrgUnitAssetAdmin": "Admin view of: Org unit asset",
    "PersonAssetAdmin": "Admin view of: Person asset",
    "UserAssetAdmin": "Admin view of: User asset",
    "CourseAdmin": "Admin view of: Course",
    "CourseCategoryAdmin": "Admin view of: Course category",
    "CourseFavAdmin": "Admin view of: Course fav",
    "CourseKitAdmin": "Admin view of: Course kit",
    "CourseKitCategoryAdmin": "Admin view of: Course kit category",
    "CourseKitFavAdmin": "Admin view of: Course kit fav",
    "CourseKitTagAdmin": "Admin view of: Course kit tag",
    "CourseTagAdmin": "Admin view of: Course tag",
    "TestAnswerAdmin": "Admin view of: Test answer",
    "TestApplyAdmin": "Admin view of: Test apply",
    "TestApplyItemAdmin": "Admin view of: Test apply item",
    "TestPaperAdmin": "Admin view of: Test paper",
    "TestPaperItemAdmin": "Admin view of: Test paper item",
    "TestQuestionAdmin": "Admin view of: Test question",
    "TestQuestionFavAdmin": "Admin view of: Test question fav",
    "TestQuestionTagAdmin": "Admin view of: Test question tag",
    "TestQuestionTalkAdmin": "Admin view of: Test question talk",
    "TestQuestionTalkVoteAdmin": "Admin view of: Test question talk vote",
    "TestQuestionVoteAdmin": "Admin view of: Test question vote",
    "IssueAdmin": "Admin view of: Issue",
    "IssueCategoryAdmin": "Admin view of: Issue category",
    "IssueFavAdmin": "Admin view of: Issue fav",
    "IssueParameterAdmin": "Admin view of: Issue parameter",
    "IssuePhaseAdmin": "Admin view of: Issue phase",
    "IssueTagAdmin": "Admin view of: Issue tag",
    "IssueVoteAdmin": "Admin view of: Issue vote",
    "DiaryAdmin": "Admin view of: Diary",
    "DiaryCategoryAdmin": "Admin view of: Diary category",
    "DiaryParameterTypeAdmin": "Admin view of: Diary parameter type",
    "DiaryPartyAdmin": "Admin view of: Diary party",
    "DiaryPhaseAdmin": "Admin view of: Diary phase",
    "DiaryReviewAdmin": "Admin view of: Diary review",
    "DiaryReviewVoteAdmin": "Admin view of: Diary review vote",
    "DiaryTagAdmin": "Admin view of: Diary tag",
    "DiaryVoteAdmin": "Admin view of: Diary vote",
    "PlanAdmin": "Admin view of: Plan",
    "PlanCategoryAdmin": "Admin view of: Plan category",
    "PlanDoAdmin": "Admin view of: Plan do",
    "PlanDoParameterTypeAdmin": "Admin view of: Plan do parameter type",
    "PlanDoTagAdmin": "Admin view of: Plan do tag",
    "PlanDoVoteAdmin": "Admin view of: Plan do vote",
    "PlanFavAdmin": "Admin view of: Plan fav",
    "PlanParameterTypeAdmin": "Admin view of: Plan parameter type",
    "PlanPartyAdmin": "Admin view of: Plan party",
    "PlanPhaseAdmin": "Admin view of: Plan phase",
    "PlanTagAdmin": "Admin view of: Plan tag",
    "PlanVoteAdmin": "Admin view of: Plan vote",
    "CartItemAdmin": "Admin view of: Cart item",
    "SalesCategoryAdmin": "Admin view of: Sales category",
    "SalesOrderAdmin": "Admin view of: Sales order",
    "SalesOrderItemAdmin": "Admin view of: Sales order item",
    "SalesPhaseAdmin": "Admin view of: Sales phase",
    "SellPriceAdmin": "Admin view of: Sell price",
    "ShopAdmin": "Admin view of: Shop",
    "ShopCategoryAdmin": "Admin view of: Shop category",
    "ShopFavAdmin": "Admin view of: Shop fav",
    "ShopItemAdmin": "Admin view of: Shop item",
    "ShopItemCategoryAdmin": "Admin view of: Shop item category",
    "ShopItemFavAdmin": "Admin view of: Shop item fav",
    "ShopTagAdmin": "Admin view of: Shop tag",
    "OffStoreItemAdmin": "Admin view of: Off store item",
    "RegionAdmin": "Admin view of: Region",
    "RegionCategoryAdmin": "Admin view of: Region category",
    "RegionLevelAdmin": "Admin view of: Region level",
    "RegionTagAdmin": "Admin view of: Region tag",
    "StoreCategoryAdmin": "Admin view of: Store category",
    "StoreItemAdmin": "Admin view of: Store item",
    "StoreOrderAdmin": "Admin view of: Store order",
    "StoreOrderItemAdmin": "Admin view of: Store order item",
    "StorePhaseAdmin": "Admin view of: Store phase",
    "TransportCategoryAdmin": "Admin view of: Transport category",
    "TransportOrderAdmin": "Admin view of: Transport order",
    "TransportOrderItemAdmin": "Admin view of: Transport order item",
    "TransportPhaseAdmin": "Admin view of: Transport phase",
};

export const routes = [
    { path: '/', component: () => import('./Index.vue') },
    { path: '/Project', component: () => import('@skeljs/core/src/ui/demo/Project.vue') },
    { path: '/ArtifactAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactAdmin.vue') },
    { path: '/ArtifactBackrefAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactBackrefAdmin.vue') },
    { path: '/ArtifactCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactCategoryAdmin.vue') },
    { path: '/ArtifactDocAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactDocAdmin.vue') },
    { path: '/ArtifactParamAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactParamAdmin.vue') },
    { path: '/ArtifactPhaseAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactPhaseAdmin.vue') },
    { path: '/ArtifactTagAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactTagAdmin.vue') },
    { path: '/ArtifactTypeAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactTypeAdmin.vue') },
    { path: '/ArtifactTypeParamAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactTypeParamAdmin.vue') },
    { path: '/ArtifactVoteAdmin', component: () => import('../src/net/bodz/violet/schema/art/ArtifactVoteAdmin.vue') },
    { path: '/StdParameterAdmin', component: () => import('../src/net/bodz/violet/schema/art/StdParameterAdmin.vue') },
    { path: '/AssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/AssetAdmin.vue') },
    { path: '/GroupAssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/GroupAssetAdmin.vue') },
    { path: '/OrgAssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/OrgAssetAdmin.vue') },
    { path: '/OrgUnitAssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/OrgUnitAssetAdmin.vue') },
    { path: '/PersonAssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/PersonAssetAdmin.vue') },
    { path: '/UserAssetAdmin', component: () => import('../src/net/bodz/violet/schema/asset/UserAssetAdmin.vue') },
    { path: '/CourseAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseAdmin.vue') },
    { path: '/CourseCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseCategoryAdmin.vue') },
    { path: '/CourseFavAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseFavAdmin.vue') },
    { path: '/CourseKitAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseKitAdmin.vue') },
    { path: '/CourseKitCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseKitCategoryAdmin.vue') },
    { path: '/CourseKitFavAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseKitFavAdmin.vue') },
    { path: '/CourseKitTagAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseKitTagAdmin.vue') },
    { path: '/CourseTagAdmin', component: () => import('../src/net/bodz/violet/schema/edu/CourseTagAdmin.vue') },
    { path: '/TestAnswerAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestAnswerAdmin.vue') },
    { path: '/TestApplyAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestApplyAdmin.vue') },
    { path: '/TestApplyItemAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestApplyItemAdmin.vue') },
    { path: '/TestPaperAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestPaperAdmin.vue') },
    { path: '/TestPaperItemAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestPaperItemAdmin.vue') },
    { path: '/TestQuestionAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionAdmin.vue') },
    { path: '/TestQuestionFavAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionFavAdmin.vue') },
    { path: '/TestQuestionTagAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionTagAdmin.vue') },
    { path: '/TestQuestionTalkAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionTalkAdmin.vue') },
    { path: '/TestQuestionTalkVoteAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionTalkVoteAdmin.vue') },
    { path: '/TestQuestionVoteAdmin', component: () => import('../src/net/bodz/violet/schema/edu/TestQuestionVoteAdmin.vue') },
    { path: '/IssueAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueAdmin.vue') },
    { path: '/IssueCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueCategoryAdmin.vue') },
    { path: '/IssueFavAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueFavAdmin.vue') },
    { path: '/IssueParameterAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueParameterAdmin.vue') },
    { path: '/IssuePhaseAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssuePhaseAdmin.vue') },
    { path: '/IssueTagAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueTagAdmin.vue') },
    { path: '/IssueVoteAdmin', component: () => import('../src/net/bodz/violet/schema/issue/IssueVoteAdmin.vue') },
    { path: '/DiaryAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryAdmin.vue') },
    { path: '/DiaryCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryCategoryAdmin.vue') },
    { path: '/DiaryParameterTypeAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryParameterTypeAdmin.vue') },
    { path: '/DiaryPartyAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryPartyAdmin.vue') },
    { path: '/DiaryPhaseAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryPhaseAdmin.vue') },
    { path: '/DiaryReviewAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryReviewAdmin.vue') },
    { path: '/DiaryReviewVoteAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryReviewVoteAdmin.vue') },
    { path: '/DiaryTagAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryTagAdmin.vue') },
    { path: '/DiaryVoteAdmin', component: () => import('../src/net/bodz/violet/schema/plan/DiaryVoteAdmin.vue') },
    { path: '/PlanAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanAdmin.vue') },
    { path: '/PlanCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanCategoryAdmin.vue') },
    { path: '/PlanDoAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanDoAdmin.vue') },
    { path: '/PlanDoParameterTypeAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanDoParameterTypeAdmin.vue') },
    { path: '/PlanDoTagAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanDoTagAdmin.vue') },
    { path: '/PlanDoVoteAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanDoVoteAdmin.vue') },
    { path: '/PlanFavAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanFavAdmin.vue') },
    { path: '/PlanParameterTypeAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanParameterTypeAdmin.vue') },
    { path: '/PlanPartyAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanPartyAdmin.vue') },
    { path: '/PlanPhaseAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanPhaseAdmin.vue') },
    { path: '/PlanTagAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanTagAdmin.vue') },
    { path: '/PlanVoteAdmin', component: () => import('../src/net/bodz/violet/schema/plan/PlanVoteAdmin.vue') },
    { path: '/CartItemAdmin', component: () => import('../src/net/bodz/violet/schema/shop/CartItemAdmin.vue') },
    { path: '/SalesCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/shop/SalesCategoryAdmin.vue') },
    { path: '/SalesOrderAdmin', component: () => import('../src/net/bodz/violet/schema/shop/SalesOrderAdmin.vue') },
    { path: '/SalesOrderItemAdmin', component: () => import('../src/net/bodz/violet/schema/shop/SalesOrderItemAdmin.vue') },
    { path: '/SalesPhaseAdmin', component: () => import('../src/net/bodz/violet/schema/shop/SalesPhaseAdmin.vue') },
    { path: '/SellPriceAdmin', component: () => import('../src/net/bodz/violet/schema/shop/SellPriceAdmin.vue') },
    { path: '/ShopAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopAdmin.vue') },
    { path: '/ShopCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopCategoryAdmin.vue') },
    { path: '/ShopFavAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopFavAdmin.vue') },
    { path: '/ShopItemAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopItemAdmin.vue') },
    { path: '/ShopItemCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopItemCategoryAdmin.vue') },
    { path: '/ShopItemFavAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopItemFavAdmin.vue') },
    { path: '/ShopTagAdmin', component: () => import('../src/net/bodz/violet/schema/shop/ShopTagAdmin.vue') },
    { path: '/OffStoreItemAdmin', component: () => import('../src/net/bodz/violet/schema/store/OffStoreItemAdmin.vue') },
    { path: '/RegionAdmin', component: () => import('../src/net/bodz/violet/schema/store/RegionAdmin.vue') },
    { path: '/RegionCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/store/RegionCategoryAdmin.vue') },
    { path: '/RegionLevelAdmin', component: () => import('../src/net/bodz/violet/schema/store/RegionLevelAdmin.vue') },
    { path: '/RegionTagAdmin', component: () => import('../src/net/bodz/violet/schema/store/RegionTagAdmin.vue') },
    { path: '/StoreCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/store/StoreCategoryAdmin.vue') },
    { path: '/StoreItemAdmin', component: () => import('../src/net/bodz/violet/schema/store/StoreItemAdmin.vue') },
    { path: '/StoreOrderAdmin', component: () => import('../src/net/bodz/violet/schema/store/StoreOrderAdmin.vue') },
    { path: '/StoreOrderItemAdmin', component: () => import('../src/net/bodz/violet/schema/store/StoreOrderItemAdmin.vue') },
    { path: '/StorePhaseAdmin', component: () => import('../src/net/bodz/violet/schema/store/StorePhaseAdmin.vue') },
    { path: '/TransportCategoryAdmin', component: () => import('../src/net/bodz/violet/schema/tran/TransportCategoryAdmin.vue') },
    { path: '/TransportOrderAdmin', component: () => import('../src/net/bodz/violet/schema/tran/TransportOrderAdmin.vue') },
    { path: '/TransportOrderItemAdmin', component: () => import('../src/net/bodz/violet/schema/tran/TransportOrderItemAdmin.vue') },
    { path: '/TransportPhaseAdmin', component: () => import('../src/net/bodz/violet/schema/tran/TransportPhaseAdmin.vue') },
];

const router = createRouter({
    history: createWebHashHistory(),
    routes: routes
});

export default router;
